name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Get Man
        uses: actions/checkout@v2
        with:
          repository: upfluence/man
          token: ${{ secrets.PAT_TOKEN }}
          ref: master
          path: upf-man

      - name: Setup gh-actions-go
        run: |
          cd upf-man
          go install -mod=vendor ./cmd/gh-actions-go-mod
          git config --global url."https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/upfluence".insteadOf "https://github.com/upfluence"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: gh-actions-go-mod -- go test -v ./...
        env:
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
