name: reviewdog
on: [pull_request]

jobs:
  lint:
    name: runner / golangci-lint
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: v1.19
      - name: Check out code
        uses: actions/checkout@v1
      - name: golanci-lint
        uses: upfluence/action-golangci-lint@master
        with:
          github_token: ${{ secrets.github_token }}
